name: Mirror Release Assets

on:
  schedule:
    - cron: '7,30 * * * *'
  workflow_dispatch:

jobs:
  Downloading_assets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    services:
      docker:
        image: xream/script-hub:latest
        ports:
          - 9100:9100
          - 9101:9101
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set repository lists
        run: |
          REPOS=(
            "NSRingo/WeatherKit"
            "NSRingo/GeoServices"
            "NSRingo/Siri"
            "NSRingo/TV"
            "NSRingo/News"
            "NSRingo/Testflight"
            "BiliUniverse/Enhanced"
            "BiliUniverse/Global"
            "BiliUniverse/Redirect"
            "BiliUniverse/ADBlock"
            "BiliUniverse/Roaming"
            "DualSubs/Universal"
            "DualSubs/YouTube"
            "DualSubs/Spotify"
            "DualSubs/Netflix"
            "DualSubs/AddOn"
          )
          echo "REPOS<<EOF" >> $GITHUB_ENV
          printf "%s\n" "${REPOS[@]}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq netcat

      - name: Wait for Docker services to be ready
        run: |
          echo "Waiting for Docker services to be ready..."
          for i in {1..10}; do
            nc -z localhost 9100 && nc -z localhost 9101 && break
            sleep 10
          done

      - name: Install sha256sum (if not available)
        run: sudo apt-get install -y coreutils

      - name: Download assets from releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ASSETS_CHANGED=false
          UPDATED_FILES=()

          # Temporary file to store sgmodule URLs that need Shadowrocket conversion
          touch sgmodule_url.txt

          while IFS= read -r REPO; do
            echo "Processing repository: $REPO"

            # Get release information
            RELEASE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$REPO/releases/latest")

            if [ -z "$RELEASE" ] || [ "$RELEASE" == "null" ] || [ "$(echo "$RELEASE" | jq -r '.message')" = "Not Found" ]; then
              echo "Release not found for $REPO, skipping."
              continue
            fi

            ASSETS=$(echo "$RELEASE" | jq -c '.assets[]')

            # Process each asset
            while IFS= read -r ASSET; do
              ASSET_NAME=$(echo "$ASSET" | jq -r '.name')
              ASSET_URL=$(echo "$ASSET" | jq -r '.url')
              ASSET_SIZE=$(echo "$ASSET" | jq -r '.size')
              BROWSER_DOWNLOAD_URL=$(echo "$ASSET" | jq -r '.browser_download_url')

              EXTENSION="${ASSET_NAME##*.}"
              echo "Found asset: $ASSET_NAME (Size: $ASSET_SIZE bytes)"

              if [[ "$REPO" == "NSRingo"* ]]; then
                if [ "$EXTENSION" = "sgmodule" ]; then
                  OUTPUT_DIR="./Modules/Surge/NSRingo"
                elif [ "$EXTENSION" = "plugin" ]; then
                  OUTPUT_DIR="./Modules/Loon/NSRingo"
                elif [ "$EXTENSION" = "srmodule" ]; then
                  OUTPUT_DIR="./Modules/Shadowrocket/NSRingo"
                else
                  continue
                fi
              elif [[ "$REPO" == "BiliUniverse"* ]]; then
                if [ "$EXTENSION" = "sgmodule" ]; then
                  OUTPUT_DIR="./Modules/Surge/BiliUniverse"
                elif [ "$EXTENSION" = "plugin" ]; then
                  OUTPUT_DIR="./Modules/Loon/BiliUniverse"
                elif [ "$EXTENSION" = "srmodule" ]; then
                  OUTPUT_DIR="./Modules/Shadowrocket/BiliUniverse"
                else
                  continue
                fi
              elif [[ "$REPO" == "DualSubs"* ]]; then
                if [ "$EXTENSION" = "sgmodule" ]; then
                  OUTPUT_DIR="./Modules/Surge/DualSubs"
                elif [ "$EXTENSION" = "plugin" ]; then
                  OUTPUT_DIR="./Modules/Loon/DualSubs"
                elif [ "$EXTENSION" = "srmodule" ]; then
                  OUTPUT_DIR="./Modules/Shadowrocket/DualSubs"
                else
                  continue
                fi
              else
                continue
              fi

              mkdir -p "$OUTPUT_DIR"
              OUTPUT_FILE="$OUTPUT_DIR/$ASSET_NAME"

              # Download the file
              curl -L -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/octet-stream" "$ASSET_URL" -o "$OUTPUT_FILE.tmp"

              if [ ! -f "$OUTPUT_FILE.tmp" ]; then
                continue
              fi

              # Checksum validation
              NEW_CHECKSUM=$(sha256sum "$OUTPUT_FILE.tmp" | awk '{ print $1 }')

              if [ -f "$OUTPUT_FILE" ]; then
                EXISTING_CHECKSUM=$(sha256sum "$OUTPUT_FILE" | awk '{ print $1 }')
                if [ "$NEW_CHECKSUM" = "$EXISTING_CHECKSUM" ]; then
                  rm "$OUTPUT_FILE.tmp"
                else
                  mv "$OUTPUT_FILE.tmp" "$OUTPUT_FILE"
                  UPDATED_FILES+=("$ASSET_NAME")
                  ASSETS_CHANGED=true
                fi
              else
                mv "$OUTPUT_FILE.tmp" "$OUTPUT_FILE"
                UPDATED_FILES+=("$ASSET_NAME")
                ASSETS_CHANGED=true
              fi

              # If `srmodule` file doesn't exist, save the `browser_download_url` to a file
              if [[ "$EXTENSION" == "sgmodule" && ! -f "$OUTPUT_DIR/$(basename "$ASSET_NAME" .sgmodule).srmodule" ]]; then
                echo "$BROWSER_DOWNLOAD_URL" >> sgmodule_url.txt
              fi

            done <<< "$ASSETS"

          done < <(printf '%s\n' "${REPOS[@]}")

          echo "ASSETS_CHANGED=$ASSETS_CHANGED" >> $GITHUB_ENV
          echo "UPDATED_FILES<<EOF" >> $GITHUB_ENV
          printf "%s\n" "${UPDATED_FILES[@]}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create unavailable modules
        run: |
          category="Jacob"
          encoded_category=$(echo "$category" | jq -sRr @uri)

          while read -r sgmodule_url; do
            # Extract the module name from the URL
            Modules_name=$(basename "$sgmodule_url" .sgmodule)
            encoded_Modules_name=$(echo "$Modules_name" | jq -sRr @uri)

            # Determine the output directory based on the repository URL
            if [[ "$sgmodule_url" == *"NSRingo"* ]]; then
              OUTPUT_DIR="./Modules/Shadowrocket/NSRingo"
            elif [[ "$sgmodule_url" == *"BiliUniverse"* ]]; then
              OUTPUT_DIR="./Modules/Shadowrocket/BiliUniverse"
            elif [[ "$sgmodule_url" == *"DualSubs"* ]]; then
              OUTPUT_DIR="./Modules/Shadowrocket/DualSubs"
            else
              echo "Unknown repository in URL: $sgmodule_url, skipping."
              continue
            fi

            # Create the output directory if it doesn't exist
            mkdir -p "$OUTPUT_DIR"

            # Construct the Shadowrocket download URL
            Shadowrocket_url="http://localhost:9100/file/_start_/${sgmodule_url}/_end_/${encoded_Modules_name}.sgmodule?type=loon-plugin&target=shadowrocket-module&category=${encoded_category}&nore=true"
            
            # Download the srmodule file
            echo "Downloading Shadowrocket module from: $Shadowrocket_url"
            curl -A "Surge Mac/2985" -L -o "${OUTPUT_DIR}/${Modules_name}.srmodule" "$Shadowrocket_url" || echo "Failed to download ${Modules_name}.srmodule"
          done < sgmodule_url.txt

      - name: Find and replace external JS resources in .sgmodule, .plugin, and .srmodule files
        continue-on-error: true
        run: |
          # (existing JS replacement logic here...)

      - name: Commit and push changes to main branch
        if: env.ASSETS_CHANGED == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # (existing commit and push logic here...)

      - name: No changes detected
        if: env.ASSETS_CHANGED != 'true'
        run: echo "No changes detected. Workflow will exit without committing."
