name: Fetch Surge sgmodule Files

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # 每天 03:00 UTC 自动运行

jobs:
  fetch-sgmodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install jq & urlencode tool
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Prepare download folder
        run: mkdir -p Modules/Surge/zirawell/Official

      - name: Fetch and download sgmodule files
        run: |
          API="https://api.github.com/repos/zirawell/R-Store/contents/Rule/Surge"
          
          # 递归获取所有文件路径
          get_files() {
            local url="$1"
            echo "Fetching: $url"
            curl -s "$url" | jq -r '.[] | [.type, .path] | @tsv' | while IFS=$'\t' read -r type path; do
              if [[ "$type" == "dir" ]]; then
                get_files "https://api.github.com/repos/zirawell/R-Store/contents/$(python3 -c "import urllib.parse; print(urllib.parse.quote('$path'))")"
              elif [[ "$path" == *.sgmodule ]]; then
                echo "$path"
              fi
            done
          }

          mapfile -t all_files < <(get_files "$API")

          echo "Found ${#all_files[@]} sgmodule files."

          # 检查重名文件
          declare -A name_count
          for f in "${all_files[@]}"; do
            base=$(basename "$f")
            name_count["$base"]=$(( ${name_count["$base"]} + 1 ))
          done

          # 下载文件，失败重试
          for f in "${all_files[@]}"; do
            base=$(basename "$f")
            dir1=$(echo "$f" | cut -d'/' -f3) # Rule/Surge/Adblock → Adblock
            if (( name_count["$base"] > 1 )); then
              save_name="${dir1}-${base}"
            else
              save_name="$base"
            fi

            echo "📥 Downloading $f as $save_name"
            for attempt in {1..3}; do
              echo "Attempt $attempt for $f"
              curl -sL \
                -H "Accept: application/vnd.github.raw" \
                "https://raw.githubusercontent.com/zirawell/R-Store/main/$(python3 -c "import urllib.parse; print(urllib.parse.quote('$f'))")" \
                -o "Modules/Surge/zirawell/Official/$save_name" && break
              sleep 2
            done
          done

      - name: Commit and push changes
        run: |
          DATE="$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')"
          
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add Modules/Surge/zirawell/Official
          if git diff --cached --quiet; then
            echo "✅ No changes to commit."
          else
            git commit -m "Download Surge Modules at $DATE (UTC+8)"
            git push
          fi
