name: Fetch sgmodule Files

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq python3

      - name: Fetch sgmodule paths
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" -s \
            "https://api.github.com/repos/zirawell/R-Store/git/trees/main?recursive=1" \
            | jq -r '.tree[] | select(.path | test("sgmodule$")) | .path' > sgmodule_paths.txt
          cat sgmodule_paths.txt

      - name: Count duplicate filenames
        run: |
          declare -A name_count
          while IFS= read -r path; do
            filename=$(basename "$path")
            name_count["$filename"]=$(( ${name_count["$filename"]} + 1 ))
          done < sgmodule_paths.txt

          # Export duplicates info for next step
          echo "DUPLICATE_FILENAMES<<EOF" >> $GITHUB_ENV
          for f in "${!name_count[@]}"; do
            echo "$f ${name_count[$f]}"
          done >> duplicate_list.txt
          cat duplicate_list.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Download sgmodule files with retry and rename duplicates
        run: |
          mkdir -p Modules/Surge/zirawell/Official
          retry=3

          # 读取重复次数到关联数组
          declare -A name_count
          while IFS= read -r line; do
            filename=$(echo "$line" | awk '{print $1}')
            count=$(echo "$line" | awk '{print $2}')
            name_count["$filename"]=$count
          done < duplicate_list.txt

          while IFS= read -r file_path; do
            filename=$(basename "$file_path")
            count=${name_count["$filename"]}
            # 获取path的第四部分作为前缀，例如 Rule/Surge/Adblock/App => App
            prefix=$(echo "$file_path" | cut -d'/' -f4)

            if [[ $count -gt 1 ]]; then
              save_name="${prefix}-${filename}"
            else
              save_name="$filename"
            fi

            echo "Downloading $file_path as $save_name"
            encoded_path=$(python3 -c "import urllib.parse; print(urllib.parse.quote('''$file_path'''))")

            attempt=1
            success=0
            while [ $attempt -le $retry ]; do
              echo "Attempt $attempt for $file_path"
              curl -H "Authorization: token $GITHUB_TOKEN" --fail -sL \
                -H "Accept: application/vnd.github.raw" \
                "https://api.github.com/repos/zirawell/R-Store/contents/$encoded_path?ref=main" \
                -o "Modules/Surge/zirawell/Official/$save_name" && success=1 && break
              echo "Attempt $attempt failed for $file_path"
              attempt=$((attempt+1))
              sleep 2
            done

            if [ $success -ne 1 ]; then
              echo "⚠️ Warning: Failed to download $file_path after $retry attempts, skipping."
            fi
          done < sgmodule_paths.txt

      - name: Commit and push changes
        run: |
          DATE="$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')"
          
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add Modules/Surge/zirawell/Official
          if git diff --cached --quiet; then
            echo "✅ No changes to commit."
          else
            git commit -m "Download Surge Modules at $DATE (UTC+8)"
            git push
          fi
