name: Fetch sgmodule files

on:
  workflow_dispatch:

jobs:
  fetch-sgmodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get all file paths recursively
        id: list_paths
        run: |
          curl -s \
            "https://api.github.com/repos/zirawell/R-Store/git/trees/main?recursive=1" \
            | jq -r '.tree[] | select(.path | test("sgmodule")) | .path' \
            > sgmodule_paths.txt

      - name: Download each sgmodule and move into target folder
        run: |
          mkdir -p Modules/Surge/zirawell/Official
          while read -r file_path; do
            curl -sL \
              -H "Accept: application/vnd.github.raw" \
              "https://api.github.com/repos/zirawell/R-Store/contents/$file_path?ref=main" \
              -o "Modules/Surge/zirawell/Official/$(basename "$file_path")"
          done < sgmodule_paths.txt

      - name: List downloaded files
        run: ls -R Modules/Surge/zirawell/Official
