name: Merge Modules

on:
  schedule:
    - cron: '7 */1 * * *'
  workflow_dispatch:

jobs:
  Merging:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run remote merge script for all matching txt files
      run: |
        for file in Links/Merge-Modules-*.txt; do
          # 下载脚本并检查状态码
          response=$(curl -sL -w "%{http_code}" -o temp_script.py -H "Authorization: token ${{ secrets.PERSONAL_TOKENS }}" \
            https://github.com/${GITHUB_ACTOR}/ShalalaLala/raw/main/Scripts/Remote-Merge-Modules.py)
      
          # 检查状态码是否为 200
          if [ "$response" != "200" ]; then
            echo "Failed to download script. HTTP status: $response"
            cat temp_script.py # 输出内容帮助调试
            exit 1
          fi

          # 执行脚本
          python temp_script.py "$file"
        done
        
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 获取当前日期，设置为北京时间 (UTC+8)
        DATE="$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')"

        # 添加 Modules 目录中的所有更改
        git add Modules/*

        # 检查是否有更改
        if git diff --cached --quiet Modules/*; then
          echo "No changes to commit"
        else
          # 提交消息，包含动态的日期
          COMMIT_MESSAGE="Merged modules at $DATE (UTC+8)"

          # 确保仓库是最新的，避免冲突
          git fetch origin
          git pull --rebase origin main  # 假设默认分支是 main
          
          # 提交更改
          git commit -m "$COMMIT_MESSAGE"
          git push
        fi
