name: Merge Modules

on:
  schedule:
    - cron: '7 */1 * * *'  # 每小时执行一次
  workflow_dispatch:

jobs:
  Merging:
    runs-on: ubuntu-latest
    
    env:
      REPOSITORY_NAME: "${{ github.actor }}/ShalalaLala"
      REPOSITORY_PATH: "${{ github.event.repository.name }}"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Checkout private repository
      uses: actions/checkout@v3
      with:
        repository: "${{ env.REPOSITORY_NAME }}"
        token: ${{ secrets.PERSONAL_TOKENS }}
        path: ${{ env.REPOSITORY_PATH }}

    - name: Run remote merge script for all matching txt files
      run: |
        # 使用通配符找到所有符合 Merge-Modules-*.txt 的文件并执行远程合并脚本
        for file in Links/Merge-Modules-*.txt; do
          python ${{ env.REPOSITORY_PATH }}/Scripts/Remote-Merge-Modules.py "$file"
        done

    - name: Check for changes and update description if needed
      run: |
        # 获取当前日期，设置为北京时间 (UTC+8)
        DATE="$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')"

        # 遍历所有合并后的模块文件
        for file in Modules/*; do
          if [ -f "$file" ]; then
            # 获取文件内容
            GENERATED_CONTENT=$(cat "$file")
            # 获取文件中的原始描述
            ORIGINAL_DESC=$(grep "^#!desc=" "$file" || true)

            # 如果描述行需要更新（例如没有 description 行，或者内容已经过时），则更新
            if [[ -z "$ORIGINAL_DESC" || "$GENERATED_CONTENT" != "$(git show HEAD:$file)" ]]; then
              echo "Updating description in $file"

              # 使用 sed 替换或添加新的描述行
              sed -i "s|^#!desc=.*|#!desc= Merged at $DATE (UTC+8)|" "$file"
            fi
          fi
        done

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 添加所有更改
        git add Modules/*

        # 如果没有变化，跳过提交
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          # 提交消息，包含动态的日期
          COMMIT_MESSAGE="Merged modules at $DATE (UTC+8)"

          # 确保仓库是最新的，避免冲突
          git stash
          git pull --rebase  # 同步远程仓库的最新更改
          git stash pop  # 恢复之前的更改

          # 再次添加文件，进行提交
          git add Modules/*
          git commit -m "$COMMIT_MESSAGE"
          git push
        fi
