name: Restore Multiple Folders

on:
  workflow_dispatch:  # 手动触发

jobs:
  restore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 保证能访问历史 commit

      - name: Checkout deleted commit as temp
        run: |
          git fetch origin b7e9c069a3eba5fe8c14a8c79b8688f1ec9dfc47
          git checkout b7e9c069a3eba5fe8c14a8c79b8688f1ec9dfc47

      - name: Copy folders from old commit
        run: |
          mkdir -p temp_restore/Surge temp_restore/Loon temp_restore/Shadowrocket
          cp -r Modules/Surge/Kelee temp_restore/Surge/
          cp -r Modules/Loon/Kelee temp_restore/Loon/
          cp -r Modules/Shadowrocket/Kelee temp_restore/Shadowrocket/

      - name: Switch back to main and restore folders
        run: |
          git checkout main

          rm -rf Modules/Loon/Kelee
          rm -rf Modules/Surge/Kelee
          rm -rf Modules/Shadowrocket/Kelee

          # 恢复各自平台正确的文件类型
          mkdir -p Modules/Surge/Kelee
          find temp_restore/Surge/Kelee -type f -name '*.sgmodule' -exec cp {} Modules/Surge/Kelee/ \;

          mkdir -p Modules/Loon/Kelee
          find temp_restore/Loon/Kelee -type f -name '*.plugin' -exec cp {} Modules/Loon/Kelee/ \;

          mkdir -p Modules/Shadowrocket/Kelee
          find temp_restore/Shadowrocket/Kelee -type f -name '*.srmodule' -exec cp {} Modules/Shadowrocket/Kelee/

      - name: Remove temp_restore folder
        run: rm -rf temp_restore
        
      - name: Commit restored files
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Restore folder. from deleted commit"
          git push
