name: Restore Multiple Folders

on:
  workflow_dispatch:  # 手动触发

jobs:
  restore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 保证能访问历史 commit

      - name: Checkout deleted commit as temp
        run: |
          git fetch origin b7e9c069a3eba5fe8c14a8c79b8688f1ec9dfc47
          git checkout b7e9c069a3eba5fe8c14a8c79b8688f1ec9dfc47

      - name: Copy folders from old commit
        run: |
          mkdir -p temp_restore/Surge temp_restore/Loon temp_restore/Shadowrocket
          cp -r Modules/Surge/Kelee temp_restore/Surge/
          cp -r Modules/Loon/Kelee temp_restore/Loon/
          cp -r Modules/Shadowrocket/Kelee temp_restore/Shadowrocket/

      - name: Switch back to main and restore folders
        run: |
          git checkout main

          rm -rf Modules/Loon/Kelee
          rm -rf Modules/Surge/Kelee
          rm -rf Modules/Shadowrocket/Kelee

      - name: Restore Kelee folders with rsync
        run: |
          for platform in Surge Loon Shadowrocket; do
            case $platform in
              Surge)
                ext="sgmodule"
                ;;
              Loon)
                ext="plugin"
                ;;
              Shadowrocket)
                ext="srmodule"
                ;;
            esac

            src="temp_restore/$platform/Kelee"
            dest="Modules/$platform/Kelee"

            if [ -d "$src" ]; then
              mkdir -p "$dest"
              rsync -av --include='*/' --include="*.$ext" --exclude='*' "$src/" "$dest/"
            else
              echo "$platform/Kelee folder not found, skipping."
            fi
          done

      - name: Remove temp_restore folder
        run: rm -rf temp_restore
        
      - name: Commit restored files
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Restore folder. from deleted commit"
          git push
