name: Restore Modules

on:
  workflow_dispatch:  # 手动触发

jobs:
  restore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 保证能访问历史 commit

      - name: Checkout deleted commit as temp
        run: |
          git fetch origin fceb30a7953e894eb19e3f55b3827b141d99082b
          git checkout fceb30a7953e894eb19e3f55b3827b141d99082b

      - name: Copy Official folder from old commit
        run: |
          mkdir -p temp_restore
          cp -r Modules/Loon/Kelee/Official temp_restore/

      - name: Checkout back to main branch
        run: |
          git checkout main
          cp -r temp_restore/Official Modules/Loon/Kelee/

      - name: Commit restored files
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add Modules/Loon/Kelee/Official
          git commit -m "Restore Official folder from deleted commit"
          git push
