name: Restore Kelee Directory

on:
  workflow_dispatch:

jobs:
  restore:
    runs-on: ubuntu-latest

    steps:
      - name: Clone full repo history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史

      - name: Create restore branch
        run: |
          git checkout -b restore-temp

      - name: Checkout old commit with the deleted directory
        run: |
          git checkout 8b590f064ef7c8595d46927c2c0587f464351e39
          mkdir -p temp_restore
          cp -r Modules/Loon/Kelee temp_restore/

      - name: Switch back to main branch
        run: |
          git checkout -
          cp -r temp_restore/Kelee Modules/Loon/

      - name: Commit and push restored folder
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add Modules/Loon/Kelee
          git commit -m "Restore deleted directory Modules/Loon/Kelee"
          git push
