name: Delete .lpx Files

on:
  workflow_dispatch:  # 手动触发

jobs:
  clean-lpx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find and delete all .lpx files
        run: |
          find . -type f -name "*\.lpx*" -exec rm -v {} \;

      - name: Commit and push deletion
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -u  # stage deletions
          
          if git diff --cached --quiet; then
            echo "✅ No .lpx files found or already deleted. Nothing to commit."
            exit 0
          fi

          git commit -m "Delete all .lpx files from repository"
          git push
  
